spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommdb   # changed from mysql → localhost
    username: root
    password: A9861@wini#
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
